### ISSUE TITLE
로그인 기능, 페이지 추가 및 스타일 변경

### ISSUE THREAD

**Issue by sojung32** [t-world-team/celebring_fe#2]
## Todo

- [x] 셀럽 목록 페이지 추가
- [x] 메인 색상 변경
- [x] 이벤트 등록 항목 변경
- [x] 셀럽 상세 페이지 > 그룹인 경우 멤버 아바타 추가
- [x] 이벤트 컴포넌트 수정
    - 이미지 제거
    - 대상 셀럽 추가
- [x] 로그인
    - 로그인 기능 추가
    - 로그인 팝업 클릭 시 url 변경
