### ISSUE TITLE
수정사항

### ISSUE THREAD

**Issue by sojung32** [t-world-team/celebring_fe#43]
## Todo

- [ ] 셀럽페이지 내 지난 이벤트 정렬
- [ ] 이벤트 컴포넌트 주소 스타일 수정
- [ ] 이벤트 컴포넌트 클릭 이벤트
- [ ] 이벤트 페이지 내 지도 이미지 스타일 수정
