### ISSUE TITLE
[셀럽 추가 요청] 수정 사항 및 오류

### ISSUE THREAD

**Issue by sojung32** [t-world-team/celebring_fe#54]
## Description

![image](https://github.com/t-world-team/celebring_fe/assets/56745491/e870910a-d879-4261-96d1-3ecd84c48599)

## Todo

- [ ] 팝업에서 이미지 로딩 완료 전까지 확인 불가 처리
- [ ] 멤버 추가 버튼 첫번째로 고정
- [ ] 멤버 수정 시 전체 멤버 이미지 일괄 변경 오류
